/* Game order by popularity or by your own play time.
 *
 * Popularity: TriMux/share/popular/<list>.txt, one game per line, most
 * popular first (generated by tools/make_popular.py from the published sales
 * lists; see the header of each file). A line may hold alternative titles
 * separated by '|'. Games are matched by a folded title key, so
 * "Legend of Zelda, The - A Link to the Past (USA)" and "The Legend of
 * Zelda: A Link to the Past" are the same game. Games not in the list have
 * rank 0 ("sem ranking").
 *
 * Play statistics: TriMuxData/state/plays.ini, [plays] <relpath, with "="
 * and "%" %-encoded> =
 * "<times> <seconds> <last epoch>", updated by trimuxctl after each game. */
#ifndef TRIMUX_POPULAR_H
#define TRIMUX_POPULAR_H

#include "catalog.h"
#include "ini.h"

#include <stddef.h>

typedef struct {
    char *key;
    int rank;
} TmPopEntry;

typedef struct {
    TmPopEntry *e; /* sorted by key */
    size_t n;
} TmPopList;

typedef struct {
    TmPopList *lists; /* one per catalog system (may be empty) */
    size_t nlists;
} TmPopular;

/* Folded match key: lower case, accents removed, "&" -> "and", a leading
 * "the " and any ", the" dropped, then only letters and digits kept. */
void tm_popular_key(const char *title, char *out, size_t size);
/* Loads the list of every system (systems.ini key "popular", default the
 * system id). Missing files are fine (no ranking for that platform). */
int tm_popular_load(TmPopular *p, const TmCatalog *cat, const char *share_dir);
void tm_popular_free(TmPopular *p);
/* Rank (1 = most popular) of a game file in its system's list, 0 if absent. */
int tm_popular_rank(const TmPopular *p, int system, const char *relpath);
/* Size of a system's list (0 = no ranking for it). */
size_t tm_popular_count(const TmPopular *p, int system);

typedef struct {
    long times, seconds, last;
} TmPlays;

/* Reads a game's statistics (zeros when it was never played). */
void tm_plays_get(const TmIni *plays, const char *relpath, TmPlays *out);
/* Adds one session to plays.ini (atomic save). Sessions shorter than
 * min_seconds (failed starts) are not counted. */
int tm_plays_add(const char *plays_path, const char *relpath, long seconds, long now, long min_seconds);

#endif
