#!/bin/sh
# Downloads the official TrimUI Brick Pro firmware listed in firmware/official.lock,
# verifies its SHA-256 and extracts the root filesystem to build/firmware/rootfs.
# Used only for the hardware audit and for ABI smoke tests under qemu; nothing
# from it is copied into the TriMux card image.
#   fetch_firmware.sh            download + extract the update package
#   fetch_firmware.sh --libs     also regenerate firmware/libs-v1.1.1.txt
set -eu
cd "$(dirname "$0")/.."
ROOT=$(pwd)
DL=$ROOT/build/downloads
OUT=$ROOT/build/firmware
mkdir -p "$DL" "$OUT"
line=$(grep '^update|' firmware/official.lock)
url=$(echo "$line" | cut -d'|' -f2)
sum=$(echo "$line" | cut -d'|' -f3)
arc=$DL/$(basename "$url")
scripts/fetch.sh "$url" "$sum" "$arc"
if [ ! -f "$OUT/x/rootfs.fex" ]; then
    rm -rf "$OUT/pkg" "$OUT/x"
    7z x -y "$arc" -o"$OUT/pkg" >/dev/null
    img=$(find "$OUT/pkg" -name '*.awimg' | head -1)
    python3 tools/awimg.py extract "$img" "$OUT/x"
fi
if [ ! -d "$OUT/rootfs/usr/trimui" ]; then
    rm -rf "$OUT/rootfs"
    7z x -y "$OUT/x/rootfs.fex" -o"$OUT/rootfs" >/dev/null 2>&1 || true
    [ -d "$OUT/rootfs/usr/trimui" ] || { echo "rootfs extraction failed" >&2; exit 1; }
fi
python3 tools/awimg.py sunxi-mbr "$OUT/x/sunxi_mbr.fex" > "$OUT/emmc-partitions.txt"
echo "firmware $(cat "$OUT/rootfs/etc/version") extracted to $OUT/rootfs"
if [ "${1:-}" = "--libs" ]; then
    {
        echo "# Shared libraries present in TrimUI Brick Pro firmware v$(cat "$OUT/rootfs/etc/version") (lib, usr/lib, usr/trimui/lib)."
        echo "# Generated by scripts/fetch_firmware.sh --libs; used by scripts/check_abi.py."
        cd "$OUT/rootfs" && find lib usr/lib usr/trimui/lib -maxdepth 1 \( -type f -o -type l \) -name '*.so*' -printf '%f\n' | sort -u
    } > "$ROOT/firmware/libs-v1.1.1.txt"
fi
